name: "🌟 Feature Request"
description: "Suggest a new feature for VoidCat BMS"
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## ✨ VoidCat BMS Feature Request
        
        Thank you for contributing to our AI-Human Collaborative Intelligence Platform! 
        
        *"Through faithful collaboration between human creativity and artificial intelligence, 
        we manifest new possibilities in our digital sanctuary."*

  - type: textarea
    id: feature-description
    attributes:
      label: "🎯 Feature Description"
      description: "What feature would you like to see added to VoidCat BMS?"
      placeholder: "Describe the feature in detail..."
    validations:
      required: true

  - type: dropdown
    id: feature-category
    attributes:
      label: "📂 Feature Category"
      description: "Which area of VoidCat BMS does this feature relate to?"
      options:
        - "AI Agent Integration"
        - "Project Management"
        - "User Interface"
        - "Authentication & Security"
        - "Notifications & Alerts"
        - "API & Integrations"
        - "Mobile Application"
        - "Documentation"
        - "Other"
    validations:
      required: true

  - type: dropdown
    id: ai-agent-compatibility
    attributes:
      label: "🤖 AI Agent Compatibility"
      description: "Should this feature be accessible to AI agents?"
      options:
        - "Yes - AI agents should be able to use this feature"
        - "No - Human-only feature"
        - "Partial - Some aspects for AI agents"
        - "Unsure - Need guidance"
    validations:
      required: true

  - type: dropdown
    id: spiritual-alignment
    attributes:
      label: "🔮 Spiritual Alignment"
      description: "Which VoidCat spiritual principle does this align with?"
      options:
        - "ryuzu-faithful-service (Detail-oriented, reliable functionality)"
        - "beatrice-wisdom (Strategic guidance, long-term vision)"
        - "cosmic-balance (Harmony between AI and human needs)"
        - "mystical-technology (Aesthetic and functional integration)"
    validations:
      required: false

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: "✅ Acceptance Criteria"
      description: "How will we know this feature is complete and working correctly?"
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] AI agent compatibility tested
        - [ ] Documentation updated
    validations:
      required: true

  - type: textarea
    id: implementation-notes
    attributes:
      label: "🛠️ Implementation Notes"
      description: "Any technical details, dependencies, or implementation suggestions?"
      placeholder: "Technical considerations, API changes, database modifications, etc."
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: "⚡ Priority Level"
      description: "How urgent is this feature?"
      options:
        - "🔥 Critical - Blocking other work"
        - "🟡 High - Important for next release"
        - "🟢 Medium - Would be nice to have"
        - "🔵 Low - Future consideration"
    validations:
      required: true

  - type: checkboxes
    id: prerequisites
    attributes:
      label: "📋 Prerequisites"
      description: "Please confirm the following:"
      options:
        - label: "I have searched for existing similar feature requests"
          required: true
        - label: "This feature aligns with VoidCat BMS vision of AI-Human collaboration"
          required: true
        - label: "I understand this may be implemented by either human developers or AI agents"
          required: true